name: whatsapp_clone_with_flutter

description: "WhatsApp clone with Flutter"

publish_to:

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logos/